apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels: 
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: ravi2krishna/lms
        imagePullPolicy: Always
        ports:
        - containerPort: 80
